### ISSUE TITLE
Todo-list

### ISSUE THREAD

**Issue by MakuraYami** [cyraxx/pogobuf#78]
**Note:** this todo-list is for the 2.0 branch!

- [x] Create a `EnvelopeRequest` class
- [ ] Rebuild the Envelope building logic in `Client.sendEnvelopeRequest`
- [ ] Rebuild the GetMapObjects delay and retry logic in `Client.sendEnvelopeRequest`
- [ ] Clean up `EnvelopeRequest.decode` method and remove things handled in `Client`
- [ ] Rename the logging events to keep a strict and clear naming consistency between Client / Request / envelope / EnvelopeRequest
- [ ] Fix reading every response to process updates in `get_map_objects_min_refresh_seconds`
- [ ] The authentication refactor - reference #64 and #24 
- [ ] Update the wiki to all new changes and create a migration guide
- [ ] merge intermittent changes from master

**Comment by cyraxx** [comment]
Closing all issues as this repository is no longer being maintained. See README for further information.
